server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: '12345'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Bienvenu !