server:
  port: 8082

spring:
  profiles:
    active: qa

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: '12345'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Bienvenu !

---

spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: '12345'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Bienvenu !

---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: '12345'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Bienvenu !